name: Deploy To S3 And Invalridate Cloudfront

on:
  push:
    branchs:
      - main

# uses: actions/checkout@v4 깃허브의 라이브러리 gitghun marketplace에 저장되어있음
jobs:
  deploy:
    runs-on: ubuntu-latest
    setps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
